name = "TestRegistry"
uuid = "c997aecc-0a5e-49f8-a72e-b17db5f41447"
repo = "https://github.com/nkottary/TestRegistry"

[packages]
ea2dc79c-39a3-11e9-2ecd-813404230491 = { name = "Privatesh", path = "P/Privatesh" }
