name = "TestRegistry"
uuid = "c997aecc-0a5e-49f8-a72e-b17db5f41447"
repo = "https://github.com/nkottary/TestRegistry"

[packages]
cb761652-754a-11e9-1d2d-6dcc2b16127a = { name = "AnotherTest", path = "A/AnotherTest" }
