name = "TestRegistry"
uuid = "c997aecc-0a5e-49f8-a72e-b17db5f41447"
repo = "https://github.com/nkottary/TestRegistry"

[packages]
914fd8de-29fd-11e9-0a06-012b13fb43aa = { name = "TestReg", path = "T/TestReg" }
cb761652-754a-11e9-1d2d-6dcc2b16127a = { name = "AnotherTest", path = "A/AnotherTest" }
ea2dc79c-39a3-11e9-2ecd-813404230491 = { name = "Privatesh", path = "P/Privatesh" }
